# Generated by Django 6.0.7 on 2026-07-07 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StravaConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("athlete_id", models.BigIntegerField(db_index=True)),
                (
                    "athlete_firstname",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "athlete_lastname",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "athlete_profile",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("token_expires_at", models.DateTimeField()),
                ("scopes", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("disconnected", "Disconnected"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=32,
                    ),
                ),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strava_connection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Strava connection",
                "verbose_name_plural": "Strava connections",
            },
        ),
    ]
